// TEMPORARY DATA

import { finished } from "stream";

export let role = "AdminUser";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];

// ganti tanggal ke tanggal hari ini
export const scheduleCalendar = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 4, 28, 8, 0),
    end: new Date(2025, 4, 28, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 4, 28, 9, 0),
    end: new Date(2025, 4, 28, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 4, 28, 10, 0),
    end: new Date(2025, 4, 28, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 4, 28, 11, 0),
    end: new Date(2025, 4, 28, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 4, 28, 13, 0),
    end: new Date(2025, 4, 28, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 4, 28, 14, 0),
    end: new Date(2025, 4, 28, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 4, 28, 9, 0),
    end: new Date(2025, 4, 28, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 4, 28, 10, 0),
    end: new Date(2025, 4, 28, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 4, 28, 11, 0),
    end: new Date(2025, 4, 28, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2025, 4, 23, 14, 0),
    end: new Date(2025, 4, 23, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 4, 24, 8, 0),
    end: new Date(2025, 4, 24, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 4, 24, 10, 0),
    end: new Date(2025, 4, 24, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 4, 24, 13, 0),
    end: new Date(2025, 4, 24, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 4, 24, 14, 0),
    end: new Date(2025, 4, 23, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 4, 25, 9, 0),
    end: new Date(2025, 4, 25, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 4, 25, 10, 0),
    end: new Date(2025, 4, 25, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 4, 25, 11, 0),
    end: new Date(2025, 4, 25, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2025, 4, 25, 14, 0),
    end: new Date(2025, 4, 25, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 4, 26, 8, 0),
    end: new Date(2025, 4, 26, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 4, 26, 9, 0),
    end: new Date(2025, 4, 26, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 4, 26, 11, 0),
    end: new Date(2025, 4, 26, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 4, 26, 13, 0),
    end: new Date(2025, 4, 26, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 4, 26, 14, 0),
    end: new Date(2025, 4, 26, 14, 45),
  },
];

// Data dummy SPK dkk
export const employeeData = [
  {
    id: 1,
    employeeId: "2323432",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081284698523",
    role: "AdminUser",
    departement: "Finance",
    companyName: "PT. Jaya Sentosa Abadi",
    address: "Jl. Rasuna Said, Surabaya, Jawa Timur",
  },
  {
    id: 2,
    employeeId: "7890123",
    name: "Jane Smith",
    email: "jane@smith.com",
    photo:
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087812345678",
    role: "Staff",
    departement: "Marketing",
    companyName: "CV. Makmur Bersama",
    address: "Jl. Sudirman No. 10, Jakarta Pusat, DKI Jakarta",
  },
  {
    id: 3,
    employeeId: "4567890",
    name: "Michael Johnson",
    email: "michael@johnson.com",
    photo:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081198765432",
    role: "Manager",
    departement: "Human Resources",
    companyName: "PT. Global Solusi",
    address: "Jl. Gatot Subroto Kav. 5, Bandung, Jawa Barat",
  },
  {
    id: 4,
    employeeId: "1234567",
    name: "Emily Davis",
    email: "emily@davis.com",
    photo:
      "https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085623456789",
    role: "Staff",
    departement: "IT",
    companyName: "UD. Cipta Karya",
    address: "Jl. Diponegoro No. 25, Yogyakarta, DI Yogyakarta",
  },
  {
    id: 5,
    employeeId: "9012345",
    name: "David Wilson",
    email: "david@wilson.com",
    photo:
      "https://images.pexels.com/photos/1587000/pexels-photo-1587000.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081376543210",
    role: "AdminUser",
    departement: "Sales",
    companyName: "PT. Maju Mundur",
    address: "Jl. Thamrin No. 8, Medan, Sumatera Utara",
  },
  {
    id: 6,
    employeeId: "3456789",
    name: "Sophia Brown",
    email: "sophia@brown.com",
    photo:
      "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081912345678",
    role: "Staff",
    departement: "Finance",
    companyName: "CV. Abadi Sentosa",
    address: "Jl. Ahmad Yani No. 15, Semarang, Jawa Tengah",
  },
  {
    id: 7,
    employeeId: "6789012",
    name: "Oliver Miller",
    email: "oliver@miller.com",
    photo:
      "https://images.pexels.com/photos/614819/pexels-photo-614819.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "089678901234",
    role: "Manager",
    departement: "Marketing",
    companyName: "PT. Bersama Jaya",
    address: "Jl. Pahlawan No. 30, Malang, Jawa Timur",
  },
  {
    id: 8,
    employeeId: "2109876",
    name: "Ava Garcia",
    email: "ava@garcia.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081543210987",
    role: "Staff",
    departement: "Human Resources",
    companyName: "UD. Mandiri Jaya",
    address: "Jl. Veteran No. 5, Denpasar, Bali",
  },
  {
    id: 9,
    employeeId: "5432109",
    name: "Noah Rodriguez",
    email: "noah@rodriguez.com",
    photo:
      "https://images.pexels.com/photos/709320/pexels-photo-709320.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087789012345",
    role: "AdminUser",
    departement: "IT",
    companyName: "PT. Sejahtera Abadi",
    address: "Jl. Teuku Umar No. 12, Makassar, Sulawesi Selatan",
  },
  {
    id: 10,
    employeeId: "8765432",
    name: "Isabella Martinez",
    email: "isabella@martinez.com",
    photo:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081234567890",
    role: "Staff",
    departement: "Sales",
    companyName: "CV. Prima Karya",
    address: "Jl. Rajawali No. 7, Palembang, Sumatera Selatan",
  },
  {
    id: 11,
    employeeId: "1098765",
    name: "Liam Hernandez",
    email: "liam@hernandez.com",
    photo:
      "https://images.pexels.com/photos/846741/pexels-photo-846741.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085711223344",
    role: "Staff",
    departement: "Finance",
    companyName: "PT. Gemilang Investama",
    address: "Jl. Merdeka No. 20, Pontianak, Kalimantan Barat",
  },
  {
    id: 12,
    employeeId: "4321098",
    name: "Mia Gonzalez",
    email: "mia@gonzalez.com",
    photo:
      "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081309876543",
    role: "Manager",
    departement: "Marketing",
    companyName: "UD. Cemerlang",
    address: "Jl. Imam Bonjol No. 3, Manado, Sulawesi Utara",
  },
  {
    id: 13,
    employeeId: "7654321",
    name: "James Perez",
    email: "james@perez.com",
    photo:
      "https://images.pexels.com/photos/697509/pexels-photo-697509.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087856789012",
    role: "AdminUser",
    departement: "Human Resources",
    companyName: "PT. Dharma Putra",
    address: "Jl. Kartini No. 18, Ambon, Maluku",
  },
  {
    id: 14,
    employeeId: "0987654",
    name: "Charlotte Rivera",
    email: "charlotte@rivera.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085690123456",
    role: "Staff",
    departement: "IT",
    companyName: "CV. Inti Karya",
    address: "Jl. Pattimura No. 9, Jayapura, Papua",
  },
  {
    id: 15,
    employeeId: "3210987",
    name: "Benjamin Flores",
    email: "benjamin@flores.com",
    photo:
      "https://images.pexels.com/photos/1484809/pexels-photo-1484809.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081123456789",
    role: "Staff",
    departement: "Sales",
    companyName: "PT. Solusi Bangun",
    address: "Jl. Gajah Mada No. 22, Pekanbaru, Riau",
  },
  {
    id: 16,
    employeeId: "6543210",
    name: "Amelia Scott",
    email: "amelia@scott.com",
    photo:
      "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "089601234567",
    role: "AdminUser",
    departement: "Finance",
    companyName: "UD. Jaya Perkasa",
    address: "Jl. Kenanga No. 4, Samarinda, Kalimantan Timur",
  },
  {
    id: 17,
    employeeId: "9876543",
    name: "Daniel Green",
    email: "daniel@green.com",
    photo:
      "https://images.pexels.com/photos/1586994/pexels-photo-1586994.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081576543210",
    role: "Manager",
    departement: "Marketing",
    companyName: "PT. Indo Sejati",
    address: "Jl. Kebon Sirih No. 11, Padang, Sumatera Barat",
  },
  {
    id: 18,
    employeeId: "2109876",
    name: "Harper Adams",
    email: "harper@adams.com",
    photo:
      "https://images.pexels.com/photos/1181424/pexels-photo-1181424.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087712345678",
    role: "Staff",
    departement: "Human Resources",
    companyName: "CV. Mitra Usaha",
    address: "Jl. Sulawesi No. 28, Banjarmasin, Kalimantan Selatan",
  },
  {
    id: 19,
    employeeId: "5432109",
    name: "Elijah Baker",
    email: "elijah@baker.com",
    photo:
      "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081390123456",
    role: "Staff",
    departement: "IT",
    companyName: "PT. Karya Utama",
    address: "Jl. Diponegoro No. 1, Ternate, Maluku Utara",
  },
  {
    id: 20,
    employeeId: "8765432",
    name: "Abigail Nelson",
    email: "abigail@nelson.com",
    photo:
      "https://images.pexels.com/photos/1181423/pexels-photo-1181423.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085678901234",
    role: "AdminUser",
    departement: "Sales",
    companyName: "UD. Cipta Rasa",
    address: "Jl. Jend. Sudirman No. 6, Kendari, Sulawesi Tenggara",
  },
  {
    id: 21,
    employeeId: "1098765",
    name: "Alexander Carter",
    email: "alexander@carter.com",
    photo:
      "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081212345678",
    role: "Staff",
    departement: "Finance",
    companyName: "PT. Aneka Niaga",
    address: "Jl. Hayam Wuruk No. 14, Bandar Lampung, Lampung",
  },
  {
    id: 22,
    employeeId: "4321098",
    name: "Sofia Mitchell",
    email: "sofia@mitchell.com",
    photo:
      "https://images.pexels.com/photos/1382731/pexels-photo-1382731.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087823456789",
    role: "Manager",
    departement: "Marketing",
    companyName: "CV. Bintang Terang",
    address: "Jl. Basuki Rahmat No. 25, Pangkal Pinang, Bangka Belitung",
  },
  {
    id: 23,
    employeeId: "7654321",
    name: "Ethan Roberts",
    email: "ethan@roberts.com",
    photo:
      "https://images.pexels.com/photos/736716/pexels-photo-736716.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085634567890",
    role: "AdminUser",
    departement: "Human Resources",
    companyName: "PT. Cahaya Abadi",
    address: "Jl. Imam Bonjol No. 17, Gorontalo, Gorontalo",
  },
  {
    id: 24,
    employeeId: "0987654",
    name: "Ella Campbell",
    email: "ella@campbell.com",
    photo:
      "https://images.pexels.com/photos/1566412/pexels-photo-1566412.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081145678901",
    role: "Staff",
    departement: "IT",
    companyName: "UD. Harapan Jaya",
    address: "Jl. Sam Ratulangi No. 10, Mamuju, Sulawesi Barat",
  },
  {
    id: 25,
    employeeId: "3210987",
    name: "Jackson Phillips",
    email: "jackson@phillips.com",
    photo:
      "https://images.pexels.com/photos/837354/pexels-photo-837354.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "089689012345",
    role: "Staff",
    departement: "Sales",
    companyName: "PT. Sarana Mandiri",
    address: "Jl. Jend. Ahmad Yani No. 5, Kupang, Nusa Tenggara Timur",
  },
  {
    id: 26,
    employeeId: "6543210",
    name: "Scarlett Evans",
    email: "scarlett@evans.com",
    photo:
      "https://images.pexels.com/photos/1557007/pexels-photo-1557007.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081567890123",
    role: "AdminUser",
    departement: "Finance",
    companyName: "CV. Lestari Abadi",
    address: "Jl. Cokroaminoto No. 16, Mataram, Nusa Tenggara Barat",
  },
  {
    id: 27,
    employeeId: "9876543",
    name: "Lucas Edwards",
    email: "lucas@edwards.com",
    photo:
      "https://images.pexels.com/photos/936119/pexels-photo-936119.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "087701234567",
    role: "Manager",
    departement: "Marketing",
    companyName: "PT. Citra Raya",
    address: "Jl. Cut Nyak Dien No. 2, Banda Aceh, Aceh",
  },
  {
    id: 28,
    employeeId: "2109876",
    name: "Chloe Parker",
    email: "chloe@parker.com",
    photo:
      "https://images.pexels.com/photos/1181423/pexels-photo-1181423.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085612345678",
    role: "Staff",
    departement: "Human Resources",
    companyName: "UD. Unggul Bersama",
    address: "Jl. Sisingamangaraja No. 19, Pangkal Pinang, Kepulauan Riau",
  },
  {
    id: 29,
    employeeId: "5432109",
    name: "Henry White",
    email: "henry@white.com",
    photo:
      "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "081323456789",
    role: "Staff",
    departement: "IT",
    companyName: "PT. Kreasi Anak Bangsa",
    address: "Jl. Sukarno Hatta No. 7, Tanjung Pinang, Kepulauan Riau",
  },
  {
    id: 30,
    employeeId: "8765432",
    name: "Grace Hall",
    email: "grace@hall.com",
    photo:
      "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "085734567890",
    role: "AdminUser",
    departement: "Sales",
    companyName: "CV. Makmur Jaya",
    address: "Jl. Diponegoro No. 3, Palu, Sulawesi Tengah",
  },
];

export const companyData = [
  {
    id: 1,
    companyId: "2323432",
    companyName: "PT. Jaya Sentosa Abadi",
    companyEmail: "info@jayasentosa.com",
    logo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081284698523",
    address: "Jl. Bendungan, Surabaya, Jawa Timur",
    tax: true,
  },
  {
    id: 2,
    companyId: "7890123",
    companyName: "CV. Makmur Bersama",
    companyEmail: "kontak@makmurbersama.co.id",
    logo: "https://images.pexels.com/photos/3184405/pexels-photo-3184405.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "087812345678",
    address: "Jl. Sudirman No. 10, Jakarta Pusat, DKI Jakarta",
    tax: false,
  },
  {
    id: 3,
    companyId: "4567890",
    companyName: "PT. Global Solusi",
    companyEmail: "admin@globalsolusi.id",
    logo: "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081198765432",
    address: "Jl. Gatot Subroto Kav. 5, Bandung, Jawa Barat",
    tax: true,
  },
  {
    id: 4,
    companyId: "1234567",
    companyName: "UD. Cipta Karya",
    companyEmail: "marketing@ciptakarya.net",
    logo: "https://images.pexels.com/photos/380768/pexels-photo-380768.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "085623456789",
    address: "Jl. Diponegoro No. 25, Yogyakarta, DI Yogyakarta",
    tax: false,
  },
  {
    id: 5,
    companyId: "9012345",
    companyName: "PT. Maju Mundur",
    companyEmail: "info@maju-mundur.com",
    logo: "https://images.pexels.com/photos/1036808/pexels-photo-1036808.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081376543210",
    address: "Jl. Thamrin No. 8, Medan, Sumatera Utara",
    tax: true,
  },
  {
    id: 6,
    companyId: "3456789",
    companyName: "CV. Abadi Sentosa",
    companyEmail: "hrd@abadisentosa.co.id",
    logo: "https://images.pexels.com/photos/159844/pexels-photo-159844.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081912345678",
    address: "Jl. Ahmad Yani No. 15, Semarang, Jawa Tengah",
    tax: false,
  },
  {
    id: 7,
    companyId: "6789012",
    companyName: "PT. Bersama Jaya",
    companyEmail: "support@bersamajaya.id",
    logo: "https://images.pexels.com/photos/1181298/pexels-photo-1181298.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "089678901234",
    address: "Jl. Pahlawan No. 30, Malang, Jawa Timur",
    tax: true,
  },
  {
    id: 8,
    companyId: "2109876",
    companyName: "UD. Mandiri Jaya",
    companyEmail: "sales@mandirijaya.net",
    logo: "https://images.pexels.com/photos/3760064/pexels-photo-3760064.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081543210987",
    address: "Jl. Veteran No. 5, Denpasar, Bali",
    tax: false,
  },
  {
    id: 9,
    companyId: "5432109",
    companyName: "PT. Sejahtera Abadi",
    companyEmail: "info@sejahteraabadi.com",
    logo: "https://images.pexels.com/photos/380769/pexels-photo-380769.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "087789012345",
    address: "Jl. Teuku Umar No. 12, Makassar, Sulawesi Selatan",
    tax: true,
  },
  {
    id: 10,
    companyId: "8765432",
    companyName: "CV. Prima Karya",
    companyEmail: "contact@primakarya.co.id",
    logo: "https://images.pexels.com/photos/3184399/pexels-photo-3184399.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081234567890",
    address: "Jl. Rajawali No. 7, Palembang, Sumatera Selatan",
    tax: false,
  },
  {
    id: 11,
    companyId: "1098765",
    companyName: "PT. Gemilang Investama",
    companyEmail: "invest@gemilang.id",
    logo: "https://images.pexels.com/photos/2675001/pexels-photo-2675001.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "085711223344",
    address: "Jl. Merdeka No. 20, Pontianak, Kalimantan Barat",
    tax: true,
  },
  {
    id: 12,
    companyId: "4321098",
    companyName: "UD. Cemerlang",
    companyEmail: "order@cemerlang.net",
    logo: "https://images.pexels.com/photos/159844/pexels-photo-159844.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081309876543",
    address: "Jl. Imam Bonjol No. 3, Manado, Sulawesi Utara",
    tax: false,
  },
  {
    id: 13,
    companyId: "7654321",
    companyName: "PT. Dharma Putra",
    companyEmail: "info@dharmaputra.com",
    logo: "https://images.pexels.com/photos/1779489/pexels-photo-1779489.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "087856789012",
    address: "Jl. Kartini No. 18, Ambon, Maluku",
    tax: true,
  },
  {
    id: 14,
    companyId: "0987654",
    companyName: "CV. Inti Karya",
    companyEmail: "marketing@intikarya.co.id",
    logo: "https://images.pexels.com/photos/3184407/pexels-photo-3184407.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "085690123456",
    address: "Jl. Pattimura No. 9, Jayapura, Papua",
    tax: false,
  },
  {
    id: 15,
    companyId: "3210987",
    companyName: "PT. Solusi Bangun",
    companyEmail: "admin@solusibangun.id",
    logo: "https://images.pexels.com/photos/380766/pexels-photo-380766.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081123456789",
    address: "Jl. Gajah Mada No. 22, Pekanbaru, Riau",
    tax: true,
  },
  {
    id: 16,
    companyId: "6543210",
    companyName: "UD. Jaya Perkasa",
    companyEmail: "support@jayaperkasa.net",
    logo: "https://images.pexels.com/photos/380765/pexels-photo-380765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "089601234567",
    address: "Jl. Kenanga No. 4, Samarinda, Kalimantan Timur",
    tax: false,
  },
  {
    id: 17,
    companyId: "9876543",
    companyName: "PT. Indo Sejati",
    companyEmail: "info@indosejati.com",
    logo: "https://images.pexels.com/photos/1181298/pexels-photo-1181298.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081576543210",
    address: "Jl. Kebon Sirih No. 11, Padang, Sumatera Barat",
    tax: true,
  },
  {
    id: 18,
    companyId: "2109876",
    companyName: "CV. Mitra Usaha",
    companyEmail: "partnership@mitrausaha.co.id",
    logo: "https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "087712345678",
    address: "Jl. Sulawesi No. 28, Banjarmasin, Kalimantan Selatan",
    tax: false,
  },
  {
    id: 19,
    companyId: "5432109",
    companyName: "PT. Karya Utama",
    companyEmail: "projects@karyautama.id",
    logo: "https://images.pexels.com/photos/1779484/pexels-photo-1779484.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "081390123456",
    address: "Jl. Diponegoro No. 1, Ternate, Maluku Utara",
    tax: true,
  },
  {
    id: 20,
    companyId: "8765432",
    companyName: "UD. Cipta Rasa",
    companyEmail: "order@ciptarasa.net",
    logo: "https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=1200",
    contact: "085678901234",
    address: "Jl. Jend. Sudirman No. 6, Kendari, Sulawesi Tenggara",
    tax: false,
  },
];

export const sparePartData = [
  {
    id: 1,
    partNumber: "KM006102A1",
    sku: "MIT-FF-KM006102A1-A",
    partName: "Fuel Filter",
    variant: "oem", // ["oem","aftermarket","gbox"]
    make: "Mitsubishi",
    suitable_for_vehicles: ["Canter Euro 4", "Mitsubishi L300"],
    price: "Rp. 75.000",
    unit: "pcs",
  },
  {
    id: 2,
    partNumber: "TY8765B2",
    sku: "TOY-BF-TY8765B2-B",
    partName: "Brake Fluid",
    variant: "aftermarket",
    make: "Toyota",
    suitable_for_vehicles: ["Avanza", "Rush", "Kijang Innova"],
    price: "Rp. 50.000",
    unit: "liter",
  },
  {
    id: 3,
    partNumber: "HD1234C3",
    sku: "HON-AC-HD1234C3-C",
    partName: "Air Conditioner Filter",
    variant: "gbox",
    make: "Honda",
    suitable_for_vehicles: ["CRV", "HRV", "Jazz"],
    price: "Rp. 90.000",
    unit: "pcs",
  },
  {
    id: 4,
    partNumber: "SU9876D4",
    sku: "SUZ-OP-SU9876D4-D",
    partName: "Oil Pan Gasket",
    variant: "oem",
    make: "Suzuki",
    suitable_for_vehicles: ["Ertiga", "XL7", "Carry"],
    price: "Rp. 35.000",
    unit: "pcs",
  },
  {
    id: 5,
    partNumber: "DA5432E5",
    sku: "DAI-SP-DA5432E5-E",
    partName: "Spark Plug",
    variant: "aftermarket",
    make: "Daihatsu",
    suitable_for_vehicles: ["Xenia", "Terios", "Rocky"],
    price: "Rp. 25.000",
    unit: "pcs",
  },
  {
    id: 6,
    partNumber: "NS2109F6",
    sku: "NIS-WT-NS2109F6-F",
    partName: "Water Pump",
    variant: "gbox",
    make: "Nissan",
    suitable_for_vehicles: ["Grand Livina", "Juke", "X-Trail"],
    price: "Rp. 300.000",
    unit: "pcs",
  },
  {
    id: 7,
    partNumber: "MI3456G7",
    sku: "MIT-RB-MI3456G7-G",
    partName: "Rear Brake Pad",
    variant: "oem",
    make: "Mitsubishi",
    suitable_for_vehicles: ["Pajero Sport", "Outlander Sport"],
    price: "Rp. 250.000",
    unit: "set",
  },
  {
    id: 8,
    partNumber: "TY0011H8",
    sku: "TOY-OF-TY0011H8-H",
    partName: "Oil Filter",
    variant: "aftermarket",
    make: "Toyota",
    suitable_for_vehicles: ["Fortuner", "Hilux", "Vios"],
    price: "Rp. 40.000",
    unit: "pcs",
  },
  {
    id: 9,
    partNumber: "HD7788I9",
    sku: "HON-FT-HD7788I9-I",
    partName: "Fan Belt",
    variant: "gbox",
    make: "Honda",
    suitable_for_vehicles: ["Civic", "Brio", "Mobilio"],
    price: "Rp. 120.000",
    unit: "pcs",
  },
  {
    id: 10,
    partNumber: "SU6655J0",
    sku: "SUZ-TP-SU6655J0-J",
    partName: "Throttle Position Sensor",
    variant: "oem",
    make: "Suzuki",
    suitable_for_vehicles: ["APV", "SX4 S-Cross"],
    price: "Rp. 180.000",
    unit: "pcs",
  },
  {
    id: 11,
    partNumber: "DA9900K1",
    sku: "DAI-WP-DA9900K1-K",
    partName: "Wiper Blade",
    variant: "aftermarket",
    make: "Daihatsu",
    suitable_for_vehicles: ["Sirion", "Ayla", "Sigra"],
    price: "Rp. 60.000",
    unit: "set",
  },
  {
    id: 12,
    partNumber: "NS4433L2",
    sku: "NIS-CL-NS4433L2-L",
    partName: "Clutch Kit",
    variant: "gbox",
    make: "Nissan",
    suitable_for_vehicles: ["March", "Serena", "Navara"],
    price: "Rp. 800.000",
    unit: "set",
  },
  {
    id: 13,
    partNumber: "MI1122M3",
    sku: "MIT-RP-MI1122M3-M",
    partName: "Radiator Hose",
    variant: "oem",
    make: "Mitsubishi",
    suitable_for_vehicles: ["Lancer", "Mirage"],
    price: "Rp. 95.000",
    unit: "pcs",
  },
  {
    id: 14,
    partNumber: "TY3344N4",
    sku: "TOY-FB-TY3344N4-N",
    partName: "Front Brake Disc",
    variant: "aftermarket",
    make: "Toyota",
    suitable_for_vehicles: ["Corolla Altis", "Camry"],
    price: "Rp. 350.000",
    unit: "pcs",
  },
  {
    id: 15,
    partNumber: "HD5566O5",
    sku: "HON-ACF-HD5566O5-O",
    partName: "Cabin Air Filter",
    variant: "gbox",
    make: "Honda",
    suitable_for_vehicles: ["Accord", "City"],
    price: "Rp. 70.000",
    unit: "pcs",
  },
  {
    id: 16,
    partNumber: "SU7788P6",
    sku: "SUZ-SF-SU7788P6-P",
    partName: "Shock Absorber Front",
    variant: "oem",
    make: "Suzuki",
    suitable_for_vehicles: ["Ignis", "Baleno"],
    price: "Rp. 400.000",
    unit: "pcs",
  },
  {
    id: 17,
    partNumber: "DA8899Q7",
    sku: "DAI-RF-DA8899Q7-Q",
    partName: "Radiator Fan Motor",
    variant: "aftermarket",
    make: "Daihatsu",
    suitable_for_vehicles: ["Gran Max", "Luxio"],
    price: "Rp. 280.000",
    unit: "pcs",
  },
  {
    id: 18,
    partNumber: "NS0011R8",
    sku: "NIS-SS-NS0011R8-R",
    partName: "Steering Rack Bushing",
    variant: "gbox",
    make: "Nissan",
    suitable_for_vehicles: ["Teana", "Elgrand"],
    price: "Rp. 65.000",
    unit: "pcs",
  },
  {
    id: 19,
    partNumber: "MI2233S9",
    sku: "MIT-EC-MI2233S9-S",
    partName: "Engine Coolant",
    variant: "oem",
    make: "Mitsubishi",
    suitable_for_vehicles: ["Canter", "Fuso"],
    price: "Rp. 150.000",
    unit: "liter",
  },
  {
    id: 20,
    partNumber: "TY4455T0",
    sku: "TOY-AB-TY4455T0-T",
    partName: "Alternator Belt",
    variant: "aftermarket",
    make: "Toyota",
    suitable_for_vehicles: ["Calya", "Sienta"],
    price: "Rp. 110.000",
    unit: "pcs",
  },
];

export const vehicleData = [
  {
    id: 1,
    licensePlate: "B 9867 NCG",
    make: "MITSUBISHI",
    model: "canter",
    trimLevel: "FE 84 SHDX",
    modelYear: "2020",
    bodyStyle: "Box Body", // ["Flat Deck", "Wing Box"]
    color: "Yellow",
  },
  {
    id: 2,
    licensePlate: "L 1234 XY",
    make: "TOYOTA",
    model: "avanza",
    trimLevel: "G 1.3 M/T",
    modelYear: "2018",
    bodyStyle: "MPV",
    color: "Silver",
  },
  {
    id: 3,
    licensePlate: "DK 5678 AB",
    make: "HONDA",
    model: "hrv",
    trimLevel: "E CVT",
    modelYear: "2021",
    bodyStyle: "SUV",
    color: "White",
  },
  {
    id: 4,
    licensePlate: "AD 9012 CD",
    make: "SUZUKI",
    model: "ertiga",
    trimLevel: "GL M/T",
    modelYear: "2019",
    bodyStyle: "MPV",
    color: "Grey",
  },
  {
    id: 5,
    licensePlate: "N 3456 EF",
    make: "DAIHATSU",
    model: "gran max",
    trimLevel: "PU 1.3",
    modelYear: "2022",
    bodyStyle: "Flat Deck",
    color: "Blue",
  },
  {
    id: 6,
    licensePlate: "D 7890 GH",
    make: "NISSAN",
    model: "grand livina",
    trimLevel: "SV A/T",
    modelYear: "2017",
    bodyStyle: "MPV",
    color: "Black",
  },
  {
    id: 7,
    licensePlate: "P 1122 IJ",
    make: "ISUZU",
    model: "elf",
    trimLevel: "NMR 71",
    modelYear: "2023",
    bodyStyle: "Box Body",
    color: "White",
  },
  {
    id: 8,
    licensePlate: "KT 3344 KL",
    make: "HINO",
    model: "dutro",
    trimLevel: "130 HD",
    modelYear: "2019",
    bodyStyle: "Dump Truck",
    color: "Green",
  },
  {
    id: 9,
    licensePlate: "AA 5566 MN",
    make: "MITSUBISHI",
    model: "xpander",
    trimLevel: "Ultimate A/T",
    modelYear: "2020",
    bodyStyle: "MPV",
    color: "Red",
  },
  {
    id: 10,
    licensePlate: "AB 7788 OP",
    make: "TOYOTA",
    model: "kijang innova",
    trimLevel: "Reborn G Diesel A/T",
    modelYear: "2021",
    bodyStyle: "MPV",
    color: "Bronze",
  },
  {
    id: 11,
    licensePlate: "B 9900 QR",
    make: "HONDA",
    model: "brio",
    trimLevel: "RS CVT",
    modelYear: "2022",
    bodyStyle: "Hatchback",
    color: "Orange",
  },
  {
    id: 12,
    licensePlate: "W 1212 ST",
    make: "SUZUKI",
    model: "carry",
    trimLevel: "PU Flat Deck",
    modelYear: "2020",
    bodyStyle: "Flat Deck",
    color: "White",
  },
  {
    id: 13,
    licensePlate: "AG 3434 UV",
    make: "DAIHATSU",
    model: "terios",
    trimLevel: "R Deluxe A/T",
    modelYear: "2018",
    bodyStyle: "SUV",
    color: "Black",
  },
  {
    id: 14,
    licensePlate: "F 5656 WX",
    make: "NISSAN",
    model: "serena",
    trimLevel: "Highway Star",
    modelYear: "2017",
    bodyStyle: "MPV",
    color: "White",
  },
  {
    id: 15,
    licensePlate: "Z 7878 YZ",
    make: "MITSUBISHI",
    model: "l300",
    trimLevel: "PU Standard",
    modelYear: "2023",
    bodyStyle: "Flat Deck",
    color: "White",
  },
  {
    id: 16,
    licensePlate: "DR 9090 AA",
    make: "TOYOTA",
    model: "rush",
    trimLevel: "TRD Sportivo A/T",
    modelYear: "2019",
    bodyStyle: "SUV",
    color: "Red",
  },
  {
    id: 17,
    licensePlate: "S 1111 BB",
    make: "HONDA",
    model: "mobilio",
    trimLevel: "RS M/T",
    modelYear: "2020",
    bodyStyle: "MPV",
    color: "Crystal Black Pearl",
  },
  {
    id: 18,
    licensePlate: "DD 2222 CC",
    make: "SUZUKI",
    model: "xl7",
    trimLevel: "Alpha A/T",
    modelYear: "2021",
    bodyStyle: "SUV",
    color: "Khaki Green",
  },
  {
    id: 19,
    licensePlate: "G 3333 DD",
    make: "DAIHATSU",
    model: "ayla",
    trimLevel: "X M/T",
    modelYear: "2022",
    bodyStyle: "Hatchback",
    color: "Yellow",
  },
  {
    id: 20,
    licensePlate: "BE 4444 EE",
    make: "MITSUBISHI",
    model: "pajero sport",
    trimLevel: "Dakar 4x2 A/T",
    modelYear: "2023",
    bodyStyle: "SUV",
    color: "Deep Bronze Metallic",
  },
];
