#docker-compose version: '3.8'
version: '3.8'

services:
  db: 
    image: postgres:latest
    restart: always
    environment:
      POSTGRESS_DB: arkstokdb
      POSTGRES_USER: arkstokuser
      POSTGRES_PASSWORD: arkstokpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local

