
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: arkstokdb
      POSTGRES_USER: arkstokuser
      POSTGRES_PASSWORD: arkstokpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Referensi ke volume db_data

  app:
    build:
      context: . 
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000" # Map port 3000 dari container ke port 3000 di host
    environment:
      DATABASE_URL: "postgresql://arkstokuser:arkstokpassword@db:5432/arkstokdb?schema=public"
    env_file:
      - .env
    depends_on:
      - db 
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  db_data:
    driver: local
