services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder 
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
    environment:
      - NODE_ENV=development 
      - DATABASE_URL=${DATABASE_URL} 
    command: "npm run dev"
    # Hapus baris 'server.js' karena kita akan menjalankan dev server Next.js
    # CMD ["node", "server.js"] # Hapus atau komen baris ini di Dockerfile jika ada

  # Service untuk menjalankan perintah CLI seperti Prisma dan seeding
  cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder 
    volumes:
      - .:/app 
    environment:
      - NODE_ENV=development 
      - DATABASE_URL=${DATABASE_URL} 
    command: "tail -f /dev/null" 
